version: '3'
networks:
  network:
    driver: bridge
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "4000:4000"
    networks:
      - network
    depends_on:
      - mariadb
    command: /bin/bash -lc "mix phx.server"
    environment:
      - PORT:80
  mariadb:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: phoenixdb
    ports:
      - "3306:3306"
    networks:
      - network
